# Generated by Django 4.1.6 on 2023-02-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_coffee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='coffee',
            options={'verbose_name_plural': 'Coffee'},
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('coffee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='home.coffee')),
            ],
        ),
    ]
